spring:
  sql:
    init:
      platform: "postgres"

  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "admin"

  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ZOM100
          jwk-set-uri: http://localhost:8080/realms/ZOM100/protocol/openid-connect/certs

logging:
  level:
    org.springframework.boot: DEBUG
